### ISSUE TITLE
applicationServerPublicKey has already been declared

### ISSUE THREAD

**Issue by joeshub** [schn4ck/schnack#57] opened 2018-02-11 01:30 UTC
This JS error is coming up.

```
Uncaught SyntaxError: Identifier 'applicationServerPublicKey' has already been declared
```

Looks like its due to the `const` declarations in push.js
https://github.com/schn4ck/schnack/blob/aeea72bffa889ba9babcea8f3af2b2909a6943d2/src/embed/push.js#L2

Would it work if we did something like? I can try and send in a PR if need be. Thank you!

```js
const applicationServerPublicKey = window.applicationServerPublicKey || '%VAPID_PUBLIC_KEY%';
const schnack_host = window.applicationServerPublicKey || '%SCHNACK_HOST%';

const serviceWorkerName =  window.applicationServerPublicKey || '/sw.js';
```

**Comment by g-div** [comment] 2018-02-11 11:11
No, I think this won't work. The problem is that a `const` variable can't be declared twice, regardless of the value assigned to it. Assigning another value to `applicationServerPublicKey` will not make any difference.
It seems much more likely that you are calling the script twice. You should check that you are embedding *schnack* only once per page.

**Comment by joeshub** [comment] 2018-02-13 05:02
Ah yes, totally right. In any case to fix this issue, I ended up having to modify `if (data.user && data.user.admin) {` in `src/embed/index.js` and add a localStorage item to track whether push.js has been loaded and avoid adding it.

eg. 
```js
if (data.user && data.user.admin && window.localStorage.getItem('schnack-push') !== 'true') {
 // add push.js to the page
```

From what I can tell currently I have to include embed.js on each page, due to the way Gatsby operates. I could be wrong but when I put embed.js on the main template it isn't rendering the comment box at all, and required a full page refresh.

I'm hoping once #24 is implemented we can call the init method on each page load instead of re-loading embed.js which would be really nice.

At that point I would also love to write a Gatsby plugin for schnack

FWIW, here are a couple of ways other apps are doing the refresh

calling reset on a global DISQUS object
https://github.com/theplatapi/react-disqus-thread/blob/master/lib/components/DisqusThread.js#L85

setting page location on window.ga
https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby-plugin-google-analytics/src/gatsby-browser.js#L4

**Comment by g-div** [comment] 2018-02-14 14:00
#61 will be merged soon, then you will be able to simply initialize *schnack* programmately.

**Closed by g-div** 2018-02-14 14:00 UTC

**Comment by joeshub** [comment] 2018-02-14 21:58
woot! exciting thanks @g-div
